name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mk_drop_down_menu:
    path: '../'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
