name: mk_drop_down_menu
description: Tap a widget wrapped with MKDropDownMenu to show a drop down menu. The header and menu are completely customizable.
repository: https://github.com/malikwang/mk_drop_down_menu
homepage: https://github.com/malikwang/mk_drop_down_menu

version: 1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
